Repository poolifier/poolifier, pull requests merged in 2021-02, with the labels that each got.

#77 Use strict compiler flag in tsconfig
  examples/typescript/pool.ts
  package.json
  src/dynamic.ts
  src/fixed.ts
  src/index.ts
  src/workers.ts
  tsconfig.json
Labels: enhancement

#90 Added contributor list
  README.MD
  package.json
Labels: documentation

#104 Add benchmark script
  .eslintrc.js
  benchmarks/bench.js
  benchmarks/myBench.js
  benchmarks/threadWorker.js
  benchmarks/workerThreadsWorker.js
  benchmarks/workerpoolWorker.js
  examples/dynamicExample.js
  examples/multiFunctionExample.js
  examples/staticExample.js
  package-lock.json
  package.json
  src/workers.ts
Labels: enhancement

#112 Provide manual benchmark workflow
  .github/workflows/ci.yml
Labels: enhancement

#113 Only package necessary files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .npmignore
  CODE_OF_CONDUCT.md
  package.json
Labels: enhancement

#92 Provide a cluster worker pool
  benchmarks/bench.js
  benchmarks/cluster/dynamic.js
  benchmarks/cluster/fixed.js
  benchmarks/cluster/worker.js
  benchmarks/external/workerThreadsWorker.js
  benchmarks/external/workerpoolWorker.js
  benchmarks/myBench.js
  benchmarks/thread/dynamic.js
  benchmarks/thread/fixed.js
  benchmarks/thread/worker.js
  package-lock.json
  src/index.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/utility-types.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
  src/worker/worker-options.ts
  tests/pools/cluster/dynamic.test.js
  tests/pools/cluster/fixed.test.js
  tests/pools/thread/dynamic.test.js
  tests/pools/thread/fixed.test.js
  tests/worker/cluster/asyncErrorWorker.js
  tests/worker/cluster/asyncWorker.js
  tests/worker/cluster/echoWorker.js
  tests/worker/cluster/emptyWorker.js
  tests/worker/cluster/errorWorker.js
  tests/worker/cluster/testWorker.js
  tests/worker/thread/asyncWorker.js
  tests/worker/thread/echoWorker.js
  tests/worker/thread/emptyWorker.js
  tests/worker/thread/errorWorker.js
  tests/worker/thread/testWorker.js
Labels: enhancement

#120 Integrate rollup bundler
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  package-lock.json
  package.json
  rollup.config.mjs
  tsconfig.development.json
Labels: enhancement

#116 Encapsulate logic of cluster and thread worker/pool
  .vscode/launch.json
  package-lock.json
  src/index.ts
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/pool.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/worker/abstract-worker.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
Labels: enhancement

#131 Fix some format issues in MD files
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#128 Only allow primitive JSON for transfer between worker and main worker
  CHANGELOG.md
  package-lock.json
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/pool.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/utility-types.ts
  src/worker/abstract-worker.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
Labels: enhancement

#124 Add protected removeWorker member function
  package-lock.json
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/worker/abstract-worker.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
Labels: enhancement

#130 Improve JSDoc comments
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/pool.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/utility-types.ts
  src/worker/abstract-worker.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
  src/worker/worker-options.ts
Labels: documentation, enhancement

#142 Add eslint-plugin-jsdoc
  .eslintrc.js
  package-lock.json
  package.json
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/thread/dynamic.ts
  src/worker/abstract-worker.ts
Labels: documentation

#143 Use rollup-plugin-typescript2 for TS transpilation
  package-lock.json
  package.json
  rollup.config.mjs
  tsconfig.json
Labels: bug

#145 Improve property namings
  CHANGELOG.md
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/pool.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
Labels: enhancement

#146 Clean worker from pool after it was destroyed
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  tests/pools/cluster/fixed.test.js
Labels: enhancement

#154 De-duplicate code for workers
  src/utility-types.ts
  src/worker/abstract-worker.ts
  src/worker/cluster-worker.ts
  src/worker/thread-worker.ts
Labels: enhancement

#152 Improve chooseWorker function in dynamic pools
  package-lock.json
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
Labels: enhancement

#169 Improvements for #161
  CHANGELOG.md
  package-lock.json
  src/index.ts
  src/pools/cluster/dynamic.ts
  src/pools/thread/dynamic.ts
  src/utility-types.ts
  src/worker/abstract-worker.ts
  src/worker/worker-options.ts
  tests/worker/cluster/asyncErrorWorker.js
  tests/worker/cluster/asyncWorker.js
  tests/worker/cluster/echoWorker.js
  tests/worker/cluster/emptyWorker.js
  tests/worker/cluster/errorWorker.js
  tests/worker/cluster/longRunningWorkerHardBehavior.js
  tests/worker/cluster/testWorker.js
  tests/worker/thread/asyncWorker.js
  tests/worker/thread/echoWorker.js
  tests/worker/thread/emptyWorker.js
  tests/worker/thread/errorWorker.js
  tests/worker/thread/longRunningWorkerHardBehavior.js
  tests/worker/thread/testWorker.js
Labels: enhancement

#171 Fix JSDoc
  src/worker/worker-options.ts
Labels: documentation

#175 Improve jsdoc comments
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/pools/abstract-pool.ts
  src/utility-types.ts
Labels: documentation

#203 Fix logo squashing
  README.md
Labels: documentation

#207 Configure dependabot
  .dependabot/config.yml
Labels: dependencies

#176 Extract selection strategies to classes
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  src/index.ts
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/pool-internal.ts
  src/pools/pool.ts
  src/pools/selection-strategies.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  src/worker/abstract-worker.ts
  tests/pools/abstract/abstract-pool.test.js
  tests/pools/cluster/dynamic.test.js
  tests/pools/cluster/fixed.test.js
  tests/pools/selection-strategies.test.js
  tests/pools/thread/dynamic.test.js
  tests/pools/thread/fixed.test.js
Labels: enhancement

#218 Fix tests
  tests/pools/abstract/abstract-pool.test.js
  tests/pools/cluster/dynamic.test.js
  tests/pools/thread/dynamic.test.js
  tests/worker/abstract-worker.test.js
Labels: bug

#213 Check that a pool have a minimum number of workers
  benchmarks/README.md
  benchmarks/versus-external-pools/functions/function-to-bench.js
  package-lock.json
  src/pools/abstract-pool.ts
  tests/pools/abstract/abstract-pool.test.js
  tests/pools/cluster/dynamic.test.js
  tests/pools/cluster/fixed.test.js
  tests/pools/selection-strategies.test.js
  tests/pools/thread/dynamic.test.js
  tests/pools/thread/fixed.test.js
  tests/worker/abstract-worker.test.js
  tests/worker/cluster-worker.test.js
  tests/worker/thread-worker.test.js
Labels: enhancement

#225 Removed max tasks
  CHANGELOG.md
  README.md
  benchmarks/internal/cluster/dynamic.js
  benchmarks/internal/cluster/fixed.js
  benchmarks/internal/thread/dynamic.js
  benchmarks/internal/thread/fixed.js
  benchmarks/versus-external-pools/dynamic-poolifier.js
  benchmarks/versus-external-pools/fixed-poolifier.js
  src/pools/abstract-pool.ts
  src/pools/cluster/dynamic.ts
  src/pools/cluster/fixed.ts
  src/pools/thread/dynamic.ts
  src/pools/thread/fixed.ts
  tests/pools/abstract/abstract-pool.test.js
  tests/pools/cluster/fixed.test.js
  tests/pools/selection-strategies.test.js
  tests/pools/thread/fixed.test.js
Labels: enhancement

#234 Untangle pool abstract class from worker strategy selection
  README.md
  benchmarks/versus-external-pools/threadjs.js
  benchmarks/versus-external-pools/workers/threadjs/function-to-bench-worker.js
  src/pools/abstract-pool.ts
  src/pools/pool-internal.ts
  src/pools/selection-strategies.ts
Labels: enhancement

#236 Integrate typedoc to generate code documentation.
  .eslintignore
  .gitignore
  .prettierignore
  CHANGELOG.md
  README.md
  docs/assets/css/main.css
  docs/assets/images/icons.png
  docs/assets/images/icons@2x.png
  docs/assets/images/widgets.png
  docs/assets/images/widgets@2x.png
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/classes/abstractworker.html
  docs/classes/clusterworker.html
  docs/classes/dynamicclusterpool.html
  docs/classes/dynamicthreadpool.html
  docs/classes/fixedclusterpool.html
  docs/classes/fixedthreadpool.html
  docs/classes/threadworker.html
  docs/index.html
  docs/interfaces/clusterpooloptions.html
  docs/interfaces/ipool.html
  docs/interfaces/iworker.html
  docs/interfaces/pooloptions.html
  docs/interfaces/workeroptions.html
  images/logo.png
  package-lock.json
  package.json
  rollup.config.mjs
  typedoc.json
Labels: documentation

#243 Return false instead of null tuple
  src/pools/abstract-pool.ts
  src/pools/cluster/fixed.ts
  src/pools/pool-internal.ts
  src/pools/selection-strategies.ts
  src/pools/thread/fixed.ts
Labels: enhancement
